# view set
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# db set
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/Study
    username: Study
    password: Study
    
